version: "3.4"
services:

  banking-engine:
    build:
      context: ./banking-engine/build
      dockerfile: Dockerfile.development
    container_name: banking-engine
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./banking-engine:/var/www/burency/banking-engine/build
      # - /var/www/burency/banking-engine/build/node_modules
    env_file: 
      - ./banking-engine/build/.env.development
    # links:
    #   - banking-db
    #   - kafka0
    #   - kafka1
    # depends_on:
    #   - banking-db
    #   - kafka0
    #   - kafka1
    # networks:
      # - banking-engine

  banking-db:
    image: mongo:4.0.8
    container_name: banking-db
    restart: always
    command: mongod --port 27019
    # command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
      MONGO_INITDB_DATABASE: banking-db
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./data/banking-db:/data/db
    ports:
      - "27019:27019"
    # networks:
      # - banking-db

volumes:
  banking-engine:
    driver: local

  banking-db:
    driver: local
  nginxdata: